# Generated by Django 5.2.8 on 2025-11-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Personal', 'Personal'), ('Work', 'Work'), ('Education', 'Education'), ('Health', 'Health'), ('Finance', 'Finance')], default='General', max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-Do', 'To-Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=64),
        ),
    ]
