# Generated by Django 5.2.8 on 2025-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name=104857600),
        ),
    ]
